# yaml 配置
version: "3.7"
services:
  redis507:
    image: "redis:5.0.7"
    ports:
      - "16379:6379"
  mysql8019:
    image: "mysql:8.0.19"
    ports:
      - "13306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "douyin"
      MYSQL_PASSWORD: "123456"
    volumes:
      - ./init.sql:/data/application/init.sql
    security_opt:
      - seccomp:unconfined
  douyin_app:
    build: .
    command: sh -c "./wait-for.sh redis507:6379 mysql8019:3306 -- ./douyin ./conf/config.yaml"
    depends_on:
      - mysql8019
      - redis507
    ports:
      - "8082:8081"